### ISSUE TITLE
Can't run Insolar docker container.

### ISSUE THREAD

**Issue by adlrocha** [insolar/insolar#1187]
**Describe the bug**
When I try to run Insolar's docker image I receive the following error:
```
WARN[0000] failed to load configuration from file:  Config File ".insolar" Not Found in "[/go/src/github.com/insolar/insolar]"  file="main.go:97" func=main package=main
FATA[0000] failed to load KeyStore: : [ NewKeyStore ] Failed to create keyStore: Failed to start components.: [ Start ] Failed to start keyStore: [ Load ] Could't read private key: [ read ] couldn't read keys from: ./: read .: is a directory  file="components.go:59" func=initBootstrapComponents package=main traceid=983f5294-d950-4ab2-b385-779e3616c0ef
```
**To Reproduce**
1. `docker run -ti insolar/insolar`

**Build (please complete the following information):**
 - OS: MacOS X / Docker 18.09.1

**Comment by Dzirtik** [comment]
Thank you for your interest in our project.

Now we still under development and you can't run the whole system in one container.
You can run the system locally:
`scripts/insolard/launchnet.sh -g`

If you want to participate in our testnet write me an email and I will give you a certificate.
