### ISSUE TITLE
Balance of accounts/wallets

### ISSUE THREAD

**Issue by marcelo321** [insolar/insolar#3157]
Hello, this instead of being a "bug report" is more like a question i didn't know where to make since i wasn't getting responses in insolar.io

I was wondering, unlike Bitcoin, would the amounts in the wallets be private... or public? Sorry for asking the question here and for bothering.

Happy new year!

**Comment by st-ledger** [comment]
Hi Marcelo, you can ask such questions in Insolar Telegram community chat https://t.me/insolar or Developer Community chat https://t.me/InsolarTech
