### ISSUE TITLE
垃圾项目，诈骗犯！！！！！

### ISSUE THREAD

**Issue by Aoseala** [insolar/insolar#3169]
Insolar团队公布INS:XNS最终兑换比例是1:10。但是从0.5亿的INS增发到100亿的XNS，增发200倍，给投资者10倍，将投资者资产缩水20倍。

**Comment by AnriNap** [comment]
问题已经用新的授权解决了https://mp.weixin.qq.com/s/ExaOIfo3Ev-t_y5A8Rw87Q
