### ISSUE TITLE
build method from README.md fails

### ISSUE THREAD

**Issue by uweewjnueji99i** [insolar/insolar#3270]
It fails with this:

```
build github.com/insolar/insolar/cmd/pulsard: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/home/me/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 (/home/me/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181204163529-d75b2dcb6bc8)
```

```
$ go version
go version go1.13.3 linux/amd64
```

On Ubuntu 18

**Comment by LinnikD** [comment]
Hello! 

Thanks for your report. Could you please test with Golang 1.12, as mentioned in the readme. If error repeats please provide additional info - what command do you run? Also, the full console output can be helpful.

**Comment by LinnikD** [comment]
We’ are closing the issue for now as there’s no additional info. But anyway if you face this problem again - let us know, we will find solution together.
